import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

import Footer from "@/sections/Footer";
import Navbar from "@/sections/Navbar";
import ThemeProvider from "./theme-provider";

import "./globals.css";

import NProgress from "nprogress";
import "nprogress/nprogress.css"; //** styles of nprogress **/

// import Router from "next/router";

export const metadata = {
  title: "Real Estate Project",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/favicon.ico" }],
  },
  /* import stylesheets directly in the layout or page itself. */
  // preconnect: ["https://stijndv.com"],
  // stylesheet: ["https://stijndv.com/fonts/Eudoxus-Sans.css"],
};

config.autoAddCss = false;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // NProgress.configure({ showSpinner: false });
  // const handleStart = () => {
  //   NProgress.start();
  // };

  // const handleStop = () => {
  //   NProgress.done();
  // };

  // Router.events.on("routeChangeStart", handleStart);
  // Router.events.on("routeChangeComplete", handleStop);
  // Router.events.on("routeChangeError", handleStop);

  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <header>
            <Navbar />
          </header>
          <main>{children}</main>
          <footer>
            <Footer />
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
